# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarkz_app', '0003_sharedbookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedbookmark',
            name='bookmark',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookmarkz_app.Bookmark'),
        ),
    ]
